spring:
  redis:
    host: 192.168.0.102
    port: 6379
    database: 0
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        max-idle: 8
        min-idle: 0